### PR TITLE
Hm_ticket_6

### PR DESCRIPTION
**Pull request by huntermetts**
# Description
User (Logged in or not) is welcomed with the LAST (most recently added) 20 products in the DB

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions for Change Made

```git fetch --all```

```git fetch HM-ticket-6```

Open and see that 20 products are available to see one the homepage AND if you click the product name, that you will be taken to a product details page.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Nick-T-Hansen — APPROVED** [review]
test works. 20 items and linked to the modified details form from my ticket 2

**Review by Daniel-Brewer — APPROVED** [review]
Works great

**Review by zwcrawford — APPROVED** [review]
Nice. Products display whether user is logged in or not

**Review by MissPeperr — APPROVED** [review]
Seal of approval! 👍

**Pull request merged**
