### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by huntermetts**
# Description

Setup database for sprint with Entity Framework

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions for Change Made

```git fetch --all```
```git checkout initial-setup```
Pull down and make sure data is good to go!

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by MissPeperr — APPROVED** [review]
Please merge this ASAP 👍

**Review by Daniel-Brewer — APPROVED** [review]
Great

**Review by Nick-T-Hansen — APPROVED** [review]
blindly approve this awesome stuff

**Review by zwcrawford — APPROVED** [review]
Directions

**Pull request merged**
